# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMain.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName(_fromUtf8("frmMain"))
        frmMain.resize(693, 301)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmMain.sizePolicy().hasHeightForWidth())
        frmMain.setSizePolicy(sizePolicy)
        frmMain.setMaximumSize(QtCore.QSize(693, 301))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/formworld.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmMain.setWindowIcon(icon)
        #frmMain.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(frmMain)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 442, 87))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(12, 23, 71, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.txtPro = QtGui.QLineEdit(self.groupBox)
        self.txtPro.setGeometry(QtCore.QRect(100, 20, 121, 22))
        self.txtPro.setObjectName(_fromUtf8("txtPro"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(240, 23, 51, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(12, 53, 71, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cmbSub = QtGui.QComboBox(self.groupBox)
        self.cmbSub.setGeometry(QtCore.QRect(100, 50, 121, 22))
        self.cmbSub.setObjectName(_fromUtf8("cmbSub"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(240, 53, 51, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cmbFed = QtGui.QComboBox(self.groupBox)
        self.cmbFed.setGeometry(QtCore.QRect(308, 50, 121, 22))
        self.cmbFed.setObjectName(_fromUtf8("cmbFed"))
        self.txtDatabase = QtGui.QLineEdit(self.groupBox)
        self.txtDatabase.setGeometry(QtCore.QRect(308, 20, 121, 22))
        self.txtDatabase.setObjectName(_fromUtf8("txtDatabase"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(460, 16, 81, 81))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.cmdNew = QtGui.QPushButton(self.groupBox_2)
        self.cmdNew.setGeometry(QtCore.QRect(15, 20, 50, 40))
        self.cmdNew.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/database_process.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdNew.setIcon(icon1)
        self.cmdNew.setIconSize(QtCore.QSize(32, 32))
        self.cmdNew.setObjectName(_fromUtf8("cmdNew"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 100, 231, 87))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.cmbLegLine = QtGui.QComboBox(self.groupBox_3)
        self.cmbLegLine.setGeometry(QtCore.QRect(100, 20, 121, 22))
        self.cmbLegLine.setObjectName(_fromUtf8("cmbLegLine"))
        self.cmbLegPole = QtGui.QComboBox(self.groupBox_3)
        self.cmbLegPole.setGeometry(QtCore.QRect(100, 50, 121, 22))
        self.cmbLegPole.setObjectName(_fromUtf8("cmbLegPole"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(12, 23, 71, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(12, 53, 71, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(250, 100, 291, 87))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(12, 53, 41, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.cmbLayers = QtGui.QComboBox(self.groupBox_4)
        self.cmbLayers.setGeometry(QtCore.QRect(68, 20, 169, 22))
        self.cmbLayers.setObjectName(_fromUtf8("cmbLayers"))
        self.cmbLegend = QtGui.QComboBox(self.groupBox_4)
        self.cmbLegend.setGeometry(QtCore.QRect(68, 50, 169, 22))
        self.cmbLegend.setObjectName(_fromUtf8("cmbLegend"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(12, 23, 51, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_2.setGeometry(QtCore.QRect(244, 12, 38, 32))
        self.pushButton_2.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapsearchsmall.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_3.setGeometry(QtCore.QRect(244, 48, 38, 32))
        self.pushButton_3.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapaddsmall.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 196, 531, 93))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.frame = QtGui.QFrame(self.groupBox_5)
        self.frame.setGeometry(QtCore.QRect(13, 15, 62, 62))
        self.frame.setStyleSheet(_fromUtf8("image: url(:/plugins/ElectricSystems/Resources/FormIcons/basicnreca.png);"))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.cmdAddlayer = QtGui.QPushButton(self.groupBox_5)
        self.cmdAddlayer.setGeometry(QtCore.QRect(130, 25, 50, 40))
        self.cmdAddlayer.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapadd.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdAddlayer.setIcon(icon4)
        self.cmdAddlayer.setIconSize(QtCore.QSize(32, 32))
        self.cmdAddlayer.setObjectName(_fromUtf8("cmdAddlayer"))
        self.cmdClear = QtGui.QPushButton(self.groupBox_5)
        self.cmdClear.setGeometry(QtCore.QRect(240, 25, 50, 40))
        self.cmdClear.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapdelete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdClear.setIcon(icon5)
        self.cmdClear.setIconSize(QtCore.QSize(32, 32))
        self.cmdClear.setObjectName(_fromUtf8("cmdClear"))
        self.cmdHelp = QtGui.QPushButton(self.groupBox_5)
        self.cmdHelp.setGeometry(QtCore.QRect(350, 25, 50, 40))
        self.cmdHelp.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/basichelp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdHelp.setIcon(icon6)
        self.cmdHelp.setIconSize(QtCore.QSize(32, 32))
        self.cmdHelp.setObjectName(_fromUtf8("cmdHelp"))
        self.cmdClose = QtGui.QPushButton(self.groupBox_5)
        self.cmdClose.setGeometry(QtCore.QRect(460, 25, 50, 40))
        self.cmdClose.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/basicexit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdClose.setIcon(icon7)
        self.cmdClose.setIconSize(QtCore.QSize(32, 32))
        self.cmdClose.setObjectName(_fromUtf8("cmdClose"))
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(550, 16, 131, 81))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.cmdMain = QtGui.QPushButton(self.groupBox_6)
        self.cmdMain.setGeometry(QtCore.QRect(13, 20, 50, 40))
        self.cmdMain.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapsettings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdMain.setIcon(icon8)
        self.cmdMain.setIconSize(QtCore.QSize(32, 32))
        self.cmdMain.setObjectName(_fromUtf8("cmdMain"))
        self.cmdEquip = QtGui.QPushButton(self.groupBox_6)
        self.cmdEquip.setGeometry(QtCore.QRect(68, 20, 50, 40))
        self.cmdEquip.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapinfo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdEquip.setIcon(icon9)
        self.cmdEquip.setIconSize(QtCore.QSize(32, 32))
        self.cmdEquip.setObjectName(_fromUtf8("cmdEquip"))
        self.groupBox_7 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(550, 106, 131, 183))
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.cmdCreate = QtGui.QPushButton(self.groupBox_7)
        self.cmdCreate.setGeometry(QtCore.QRect(13, 23, 50, 40))
        self.cmdCreate.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapedit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdCreate.setIcon(icon10)
        self.cmdCreate.setIconSize(QtCore.QSize(32, 32))
        self.cmdCreate.setObjectName(_fromUtf8("cmdCreate"))
        self.cmdProcess = QtGui.QPushButton(self.groupBox_7)
        self.cmdProcess.setGeometry(QtCore.QRect(68, 23, 50, 40))
        self.cmdProcess.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapgps.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdProcess.setIcon(icon11)
        self.cmdProcess.setIconSize(QtCore.QSize(32, 32))
        self.cmdProcess.setObjectName(_fromUtf8("cmdProcess"))
        self.cmdValidate = QtGui.QPushButton(self.groupBox_7)
        self.cmdValidate.setGeometry(QtCore.QRect(13, 70, 50, 40))
        self.cmdValidate.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapaccept.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdValidate.setIcon(icon12)
        self.cmdValidate.setIconSize(QtCore.QSize(32, 32))
        self.cmdValidate.setObjectName(_fromUtf8("cmdValidate"))
        self.cmdFinance = QtGui.QPushButton(self.groupBox_7)
        self.cmdFinance.setGeometry(QtCore.QRect(68, 70, 50, 40))
        self.cmdFinance.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapfinance.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdFinance.setIcon(icon13)
        self.cmdFinance.setIconSize(QtCore.QSize(32, 32))
        self.cmdFinance.setObjectName(_fromUtf8("cmdFinance"))
        self.cmdMilsoft = QtGui.QPushButton(self.groupBox_7)
        self.cmdMilsoft.setGeometry(QtCore.QRect(68, 117, 50, 40))
        self.cmdMilsoft.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapmilsoft.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdMilsoft.setIcon(icon14)
        self.cmdMilsoft.setIconSize(QtCore.QSize(32, 32))
        self.cmdMilsoft.setObjectName(_fromUtf8("cmdMilsoft"))
        self.cmdVoltage = QtGui.QPushButton(self.groupBox_7)
        self.cmdVoltage.setGeometry(QtCore.QRect(13, 117, 50, 40))
        self.cmdVoltage.setText(_fromUtf8(""))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapvoltage.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdVoltage.setIcon(icon15)
        self.cmdVoltage.setIconSize(QtCore.QSize(32, 32))
        self.cmdVoltage.setObjectName(_fromUtf8("cmdVoltage"))
        #frmMain.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmMain)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        frmMain.setWindowTitle(_translate("frmMain", "NRECA Electric Systems", None))
        self.groupBox.setTitle(_translate("frmMain", "Dataset", None))
        self.label.setText(_translate("frmMain", "User Name", None))
        self.txtPro.setToolTip(_translate("frmMain", "Project Name", None))
        self.label_2.setText(_translate("frmMain", "Database", None))
        self.label_3.setText(_translate("frmMain", "Substation", None))
        self.cmbSub.setToolTip(_translate("frmMain", "Select Substation", None))
        self.label_4.setText(_translate("frmMain", "Feeder", None))
        self.cmbFed.setToolTip(_translate("frmMain", "Select Feeder", None))
        self.txtDatabase.setToolTip(_translate("frmMain", "Project Name", None))
        self.cmdNew.setToolTip(_translate("frmMain", "Define New Project", None))
        self.groupBox_3.setTitle(_translate("frmMain", "Change Legend", None))
        self.cmbLegLine.setToolTip(_translate("frmMain", "Select Legend for Electric Line", None))
        self.cmbLegPole.setToolTip(_translate("frmMain", "Select Legend for Electric Pole", None))
        self.label_5.setText(_translate("frmMain", "Electric Line", None))
        self.label_6.setText(_translate("frmMain", "Electric Pole", None))
        self.groupBox_4.setTitle(_translate("frmMain", "LandBase", None))
        self.label_8.setText(_translate("frmMain", "Legend", None))
        self.cmbLayers.setToolTip(_translate("frmMain", "Available LandBase Layers", None))
        self.cmbLegend.setToolTip(_translate("frmMain", "Legends for LandBase Layers", None))
        self.label_7.setText(_translate("frmMain", "Layers", None))
        self.pushButton_2.setToolTip(_translate("frmMain", "Get LandBase Layers", None))
        self.pushButton_3.setToolTip(_translate("frmMain", "Add LandBase to Map", None))
        self.cmdAddlayer.setToolTip(_translate("frmMain", "Add Feeder Electric Layers", None))
        self.cmdClear.setToolTip(_translate("frmMain", "Clear Map", None))
        self.cmdHelp.setToolTip(_translate("frmMain", "Help", None))
        self.cmdClose.setToolTip(_translate("frmMain", "Close", None))
        self.cmdMain.setToolTip(_translate("frmMain", "Database Development and Analysis", None))
        self.cmdEquip.setToolTip(_translate("frmMain", "Equipment Database", None))
        self.cmdCreate.setToolTip(_translate("frmMain", "Database Intialization", None))
        self.cmdProcess.setToolTip(_translate("frmMain", "Process Field Data", None))
        self.cmdValidate.setToolTip(_translate("frmMain", "Database Validation", None))
        self.cmdFinance.setToolTip(_translate("frmMain", "Financial Analysis", None))
        self.cmdMilsoft.setToolTip(_translate("frmMain", "Database Conversion to WindMil", None))
        self.cmdVoltage.setToolTip(_translate("frmMain", "Voltage Analysis", None))

import resources

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    frmMain = QtGui.QMainWindow()
    ui = Ui_frmMain()
    ui.setupUi(frmMain)
    frmMain.show()
    sys.exit(app.exec_())
