# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmFinance.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmFinance(object):
    def setupUi(self, frmFinance):
        frmFinance.setObjectName(_fromUtf8("frmFinance"))
        frmFinance.resize(760, 450)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmFinance.sizePolicy().hasHeightForWidth())
        frmFinance.setSizePolicy(sizePolicy)
        frmFinance.setMinimumSize(QtCore.QSize(760, 450))
        frmFinance.setMaximumSize(QtCore.QSize(760, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/formfinance.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmFinance.setWindowIcon(icon)
        frmFinance.setWindowOpacity(1.0)
        self.centralwidget = QtGui.QWidget(frmFinance)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 358, 591, 83))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(94, 19, 71, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.txtPro = QtGui.QLineEdit(self.groupBox)
        self.txtPro.setEnabled(False)
        self.txtPro.setGeometry(QtCore.QRect(170, 16, 160, 22))
        self.txtPro.setToolTip(_fromUtf8(""))
        self.txtPro.setObjectName(_fromUtf8("txtPro"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(348, 19, 51, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(94, 49, 71, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(348, 49, 51, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.txtSub = QtGui.QLineEdit(self.groupBox)
        self.txtSub.setEnabled(False)
        self.txtSub.setGeometry(QtCore.QRect(170, 46, 160, 22))
        self.txtSub.setToolTip(_fromUtf8(""))
        self.txtSub.setObjectName(_fromUtf8("txtSub"))
        self.txtPBS = QtGui.QLineEdit(self.groupBox)
        self.txtPBS.setEnabled(False)
        self.txtPBS.setGeometry(QtCore.QRect(416, 16, 160, 22))
        self.txtPBS.setToolTip(_fromUtf8(""))
        self.txtPBS.setObjectName(_fromUtf8("txtPBS"))
        self.txtFed = QtGui.QLineEdit(self.groupBox)
        self.txtFed.setEnabled(False)
        self.txtFed.setGeometry(QtCore.QRect(416, 46, 160, 22))
        self.txtFed.setToolTip(_fromUtf8(""))
        self.txtFed.setObjectName(_fromUtf8("txtFed"))
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(10, 10, 62, 62))
        self.frame.setStyleSheet(_fromUtf8("image: url(:/plugins/ElectricSystems/Resources/FormIcons/basicnreca.png);"))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(610, 10, 139, 431))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.cmdInputTable = QtGui.QPushButton(self.groupBox_2)
        self.cmdInputTable.setGeometry(QtCore.QRect(17, 30, 50, 40))
        self.cmdInputTable.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/maptable.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdInputTable.setIcon(icon1)
        self.cmdInputTable.setIconSize(QtCore.QSize(32, 32))
        self.cmdInputTable.setObjectName(_fromUtf8("cmdInputTable"))
        self.cmdCreatePro = QtGui.QPushButton(self.groupBox_2)
        self.cmdCreatePro.setGeometry(QtCore.QRect(74, 30, 50, 40))
        self.cmdCreatePro.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapedit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdCreatePro.setIcon(icon2)
        self.cmdCreatePro.setIconSize(QtCore.QSize(32, 32))
        self.cmdCreatePro.setObjectName(_fromUtf8("cmdCreatePro"))
        self.cmdAddPro = QtGui.QPushButton(self.groupBox_2)
        self.cmdAddPro.setGeometry(QtCore.QRect(17, 78, 50, 40))
        self.cmdAddPro.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapadd.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdAddPro.setIcon(icon3)
        self.cmdAddPro.setIconSize(QtCore.QSize(32, 32))
        self.cmdAddPro.setObjectName(_fromUtf8("cmdAddPro"))
        self.cmdDelPro = QtGui.QPushButton(self.groupBox_2)
        self.cmdDelPro.setGeometry(QtCore.QRect(74, 78, 50, 40))
        self.cmdDelPro.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapdelete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdDelPro.setIcon(icon4)
        self.cmdDelPro.setIconSize(QtCore.QSize(32, 32))
        self.cmdDelPro.setObjectName(_fromUtf8("cmdDelPro"))
        self.cmdCalCon = QtGui.QPushButton(self.groupBox_2)
        self.cmdCalCon.setGeometry(QtCore.QRect(17, 186, 50, 40))
        self.cmdCalCon.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapcons.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdCalCon.setIcon(icon5)
        self.cmdCalCon.setIconSize(QtCore.QSize(32, 32))
        self.cmdCalCon.setObjectName(_fromUtf8("cmdCalCon"))
        self.cmdRepCon = QtGui.QPushButton(self.groupBox_2)
        self.cmdRepCon.setGeometry(QtCore.QRect(74, 186, 50, 40))
        self.cmdRepCon.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/reportconstruction.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdRepCon.setIcon(icon6)
        self.cmdRepCon.setIconSize(QtCore.QSize(32, 32))
        self.cmdRepCon.setObjectName(_fromUtf8("cmdRepCon"))
        self.cmdCalFin = QtGui.QPushButton(self.groupBox_2)
        self.cmdCalFin.setGeometry(QtCore.QRect(17, 234, 50, 40))
        self.cmdCalFin.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/mapfinancial.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdCalFin.setIcon(icon7)
        self.cmdCalFin.setIconSize(QtCore.QSize(32, 32))
        self.cmdCalFin.setObjectName(_fromUtf8("cmdCalFin"))
        self.cmdRepFin = QtGui.QPushButton(self.groupBox_2)
        self.cmdRepFin.setGeometry(QtCore.QRect(74, 234, 50, 40))
        self.cmdRepFin.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/reportfinance.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdRepFin.setIcon(icon8)
        self.cmdRepFin.setIconSize(QtCore.QSize(32, 32))
        self.cmdRepFin.setObjectName(_fromUtf8("cmdRepFin"))
        self.cmdHelp = QtGui.QPushButton(self.groupBox_2)
        self.cmdHelp.setGeometry(QtCore.QRect(17, 360, 50, 40))
        self.cmdHelp.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/basichelp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdHelp.setIcon(icon9)
        self.cmdHelp.setIconSize(QtCore.QSize(32, 32))
        self.cmdHelp.setObjectName(_fromUtf8("cmdHelp"))
        self.cmdClose = QtGui.QPushButton(self.groupBox_2)
        self.cmdClose.setGeometry(QtCore.QRect(74, 360, 50, 40))
        self.cmdClose.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/basicexit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdClose.setIcon(icon10)
        self.cmdClose.setIconSize(QtCore.QSize(32, 32))
        self.cmdClose.setObjectName(_fromUtf8("cmdClose"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 593, 341))
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabExtProjects = QtGui.QWidget()
        self.tabExtProjects.setObjectName(_fromUtf8("tabExtProjects"))
        self.tableView = QtGui.QTableView(self.tabExtProjects)
        self.tableView.setGeometry(QtCore.QRect(5, 5, 578, 295))
        self.tableView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableView.setFrameShadow(QtGui.QFrame.Plain)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/finextension.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabExtProjects, icon11, _fromUtf8(""))
        self.tabProProperties = QtGui.QWidget()
        self.tabProProperties.setObjectName(_fromUtf8("tabProProperties"))
        self.groupBox_3 = QtGui.QGroupBox(self.tabProProperties)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 280, 121))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(15, 25, 81, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(15, 55, 71, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.txtProNum = QtGui.QLineEdit(self.groupBox_3)
        self.txtProNum.setGeometry(QtCore.QRect(115, 23, 151, 20))
        self.txtProNum.setObjectName(_fromUtf8("txtProNum"))
        self.txtProName = QtGui.QLineEdit(self.groupBox_3)
        self.txtProName.setGeometry(QtCore.QRect(115, 53, 151, 20))
        self.txtProName.setObjectName(_fromUtf8("txtProName"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(15, 86, 81, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.cmbProSite = QtGui.QComboBox(self.groupBox_3)
        self.cmbProSite.setGeometry(QtCore.QRect(115, 83, 151, 22))
        self.cmbProSite.setObjectName(_fromUtf8("cmbProSite"))
        self.groupBox_4 = QtGui.QGroupBox(self.tabProProperties)
        self.groupBox_4.setGeometry(QtCore.QRect(299, 10, 280, 121))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.radSet = QtGui.QRadioButton(self.groupBox_4)
        self.radSet.setGeometry(QtCore.QRect(40, 25, 151, 17))
        self.radSet.setObjectName(_fromUtf8("radSet"))
        self.radStr = QtGui.QRadioButton(self.groupBox_4)
        self.radStr.setGeometry(QtCore.QRect(40, 55, 151, 17))
        self.radStr.setObjectName(_fromUtf8("radStr"))
        self.radVil = QtGui.QRadioButton(self.groupBox_4)
        self.radVil.setGeometry(QtCore.QRect(40, 84, 151, 17))
        self.radVil.setObjectName(_fromUtf8("radVil"))
        self.groupBox_5 = QtGui.QGroupBox(self.tabProProperties)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 135, 280, 93))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(15, 26, 81, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.cmbPrLineType = QtGui.QComboBox(self.groupBox_5)
        self.cmbPrLineType.setGeometry(QtCore.QRect(115, 23, 151, 22))
        self.cmbPrLineType.setObjectName(_fromUtf8("cmbPrLineType"))
        self.cmbPrLineVolt = QtGui.QComboBox(self.groupBox_5)
        self.cmbPrLineVolt.setGeometry(QtCore.QRect(115, 54, 151, 22))
        self.cmbPrLineVolt.setObjectName(_fromUtf8("cmbPrLineVolt"))
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(15, 57, 81, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.groupBox_6 = QtGui.QGroupBox(self.tabProProperties)
        self.groupBox_6.setGeometry(QtCore.QRect(299, 135, 280, 93))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_10 = QtGui.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(15, 26, 81, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.cmbScConSize = QtGui.QComboBox(self.groupBox_6)
        self.cmbScConSize.setGeometry(QtCore.QRect(115, 23, 151, 22))
        self.cmbScConSize.setObjectName(_fromUtf8("cmbScConSize"))
        self.txtAvgTrLen = QtGui.QLineEdit(self.groupBox_6)
        self.txtAvgTrLen.setGeometry(QtCore.QRect(215, 54, 51, 20))
        self.txtAvgTrLen.setObjectName(_fromUtf8("txtAvgTrLen"))
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(15, 57, 191, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.groupBox_7 = QtGui.QGroupBox(self.tabProProperties)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 233, 569, 63))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_12 = QtGui.QLabel(self.groupBox_7)
        self.label_12.setGeometry(QtCore.QRect(15, 26, 81, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.cmbLegLine = QtGui.QComboBox(self.groupBox_7)
        self.cmbLegLine.setGeometry(QtCore.QRect(115, 23, 151, 22))
        self.cmbLegLine.setObjectName(_fromUtf8("cmbLegLine"))
        self.cmbLegPole = QtGui.QComboBox(self.groupBox_7)
        self.cmbLegPole.setGeometry(QtCore.QRect(405, 23, 151, 22))
        self.cmbLegPole.setObjectName(_fromUtf8("cmbLegPole"))
        self.label_13 = QtGui.QLabel(self.groupBox_7)
        self.label_13.setGeometry(QtCore.QRect(290, 26, 81, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/finproperties.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabProProperties, icon12, _fromUtf8(""))
        #frmFinance.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmFinance)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(frmFinance)

    def retranslateUi(self, frmFinance):
        frmFinance.setWindowTitle(_translate("frmFinance", "Financial Analysis", None))
        self.label.setText(_translate("frmFinance", "Project", None))
        self.label_2.setText(_translate("frmFinance", "Database", None))
        self.label_3.setText(_translate("frmFinance", "Substation", None))
        self.label_4.setText(_translate("frmFinance", "Feeder", None))
        self.cmdInputTable.setToolTip(_translate("frmFinance", "Open Input Tables", None))
        self.cmdCreatePro.setToolTip(_translate("frmFinance", "Create New Extension Project", None))
        self.cmdAddPro.setToolTip(_translate("frmFinance", "Add Expansion Project to Map", None))
        self.cmdDelPro.setToolTip(_translate("frmFinance", "Delete Expension Project from Map", None))
        self.cmdCalCon.setToolTip(_translate("frmFinance", "Calculate Project Construction Cost", None))
        self.cmdRepCon.setToolTip(_translate("frmFinance", "View Project Construction Report", None))
        self.cmdCalFin.setToolTip(_translate("frmFinance", "Perform Cash Flow Analysis", None))
        self.cmdRepFin.setToolTip(_translate("frmFinance", "Show Cash Flow Report", None))
        self.cmdHelp.setToolTip(_translate("frmFinance", "Help", None))
        self.cmdClose.setToolTip(_translate("frmFinance", "Close", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExtProjects), _translate("frmFinance", "Extension Projects", None))
        self.groupBox_3.setTitle(_translate("frmFinance", "Prposed Extension Project", None))
        self.label_5.setText(_translate("frmFinance", "Project Number", None))
        self.label_6.setText(_translate("frmFinance", "Project Name", None))
        self.txtProNum.setToolTip(_translate("frmFinance", "Enter Extension Project Number", None))
        self.txtProName.setToolTip(_translate("frmFinance", "Enter Extension Project Name", None))
        self.label_7.setText(_translate("frmFinance", "Project Site", None))
        self.groupBox_4.setTitle(_translate("frmFinance", "Population Data Source", None))
        self.radSet.setText(_translate("frmFinance", "Settlement Cluster", None))
        self.radStr.setText(_translate("frmFinance", "Household Structure", None))
        self.radVil.setText(_translate("frmFinance", "Village Area", None))
        self.groupBox_5.setTitle(_translate("frmFinance", "Primary Line Design Paramaters", None))
        self.label_8.setText(_translate("frmFinance", "Line Type", None))
        self.cmbPrLineType.setToolTip(_translate("frmFinance", "Select Primary Line Type", None))
        self.cmbPrLineVolt.setToolTip(_translate("frmFinance", "Select Primary Line Voltage", None))
        self.label_9.setText(_translate("frmFinance", "Line Voltage", None))
        self.groupBox_6.setTitle(_translate("frmFinance", "Secondary Line Parameters", None))
        self.label_10.setText(_translate("frmFinance", "Conductor Size", None))
        self.cmbScConSize.setToolTip(_translate("frmFinance", "Select Secondary Conductor Size", None))
        self.txtAvgTrLen.setToolTip(_translate("frmFinance", "Enter Average Length in km per Transformer", None))
        self.label_11.setText(_translate("frmFinance", "Average Length of Transformer per km", None))
        self.groupBox_7.setTitle(_translate("frmFinance", "Change Legend", None))
        self.label_12.setText(_translate("frmFinance", "Proposed Line", None))
        self.cmbLegLine.setToolTip(_translate("frmFinance", "Select Legend for Proposed Line", None))
        self.cmbLegPole.setToolTip(_translate("frmFinance", "Select Legend for Proposed Pole", None))
        self.label_13.setText(_translate("frmFinance", "Proposed Pole", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProProperties), _translate("frmFinance", "Project Properties", None))

import resources

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    frmFinance = QtGui.QMainWindow()
    ui = Ui_frmFinance()
    ui.setupUi(frmFinance)
    frmFinance.show()
    sys.exit(app.exec_())

