# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmGPSData.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmGPSData(object):
    def setupUi(self, frmGPSData):
        frmGPSData.setObjectName(_fromUtf8("frmGPSData"))
        frmGPSData.resize(940, 530)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmGPSData.sizePolicy().hasHeightForWidth())
        frmGPSData.setSizePolicy(sizePolicy)
        frmGPSData.setMaximumSize(QtCore.QSize(940, 530))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/formgps.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmGPSData.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(frmGPSData)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 921, 86))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(87, 21, 71, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.txtPro = QtGui.QLineEdit(self.groupBox)
        self.txtPro.setEnabled(False)
        self.txtPro.setGeometry(QtCore.QRect(150, 18, 110, 22))
        self.txtPro.setToolTip(_fromUtf8(""))
        self.txtPro.setObjectName(_fromUtf8("txtPro"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(270, 21, 51, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(87, 51, 71, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(270, 51, 51, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.txtSub = QtGui.QLineEdit(self.groupBox)
        self.txtSub.setEnabled(False)
        self.txtSub.setGeometry(QtCore.QRect(150, 48, 110, 22))
        self.txtSub.setToolTip(_fromUtf8(""))
        self.txtSub.setObjectName(_fromUtf8("txtSub"))
        self.txtPBS = QtGui.QLineEdit(self.groupBox)
        self.txtPBS.setEnabled(False)
        self.txtPBS.setGeometry(QtCore.QRect(326, 18, 110, 22))
        self.txtPBS.setToolTip(_fromUtf8(""))
        self.txtPBS.setObjectName(_fromUtf8("txtPBS"))
        self.txtFed = QtGui.QLineEdit(self.groupBox)
        self.txtFed.setEnabled(False)
        self.txtFed.setGeometry(QtCore.QRect(326, 48, 110, 22))
        self.txtFed.setToolTip(_fromUtf8(""))
        self.txtFed.setObjectName(_fromUtf8("txtFed"))
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(11, 12, 62, 62))
        self.frame.setStyleSheet(_fromUtf8("image: url(:/plugins/ElectricSystems/Resources/FormIcons/basicnreca.png);"))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.cmdGPSSave = QtGui.QPushButton(self.groupBox)
        self.cmdGPSSave.setGeometry(QtCore.QRect(692, 23, 50, 40))
        self.cmdGPSSave.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/textsave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdGPSSave.setIcon(icon1)
        self.cmdGPSSave.setIconSize(QtCore.QSize(32, 32))
        self.cmdGPSSave.setObjectName(_fromUtf8("cmdGPSSave"))
        self.cmdCreateFeature = QtGui.QPushButton(self.groupBox)
        self.cmdCreateFeature.setGeometry(QtCore.QRect(747, 23, 50, 40))
        self.cmdCreateFeature.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/featurecreate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdCreateFeature.setIcon(icon2)
        self.cmdCreateFeature.setIconSize(QtCore.QSize(32, 32))
        self.cmdCreateFeature.setObjectName(_fromUtf8("cmdCreateFeature"))
        self.cmdHelp = QtGui.QPushButton(self.groupBox)
        self.cmdHelp.setGeometry(QtCore.QRect(802, 23, 50, 40))
        self.cmdHelp.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/basichelp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdHelp.setIcon(icon3)
        self.cmdHelp.setIconSize(QtCore.QSize(32, 32))
        self.cmdHelp.setObjectName(_fromUtf8("cmdHelp"))
        self.cmdClose = QtGui.QPushButton(self.groupBox)
        self.cmdClose.setGeometry(QtCore.QRect(857, 23, 50, 40))
        self.cmdClose.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/basicexit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdClose.setIcon(icon4)
        self.cmdClose.setIconSize(QtCore.QSize(32, 32))
        self.cmdClose.setObjectName(_fromUtf8("cmdClose"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(447, 51, 31, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.txtGroup = QtGui.QLineEdit(self.groupBox)
        self.txtGroup.setEnabled(False)
        self.txtGroup.setGeometry(QtCore.QRect(490, 18, 110, 22))
        self.txtGroup.setToolTip(_fromUtf8(""))
        self.txtGroup.setObjectName(_fromUtf8("txtGroup"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(447, 21, 41, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.txtDate = QtGui.QLineEdit(self.groupBox)
        self.txtDate.setEnabled(False)
        self.txtDate.setGeometry(QtCore.QRect(490, 48, 110, 22))
        self.txtDate.setToolTip(_fromUtf8(""))
        self.txtDate.setObjectName(_fromUtf8("txtDate"))
        self.cmdGPSEdit = QtGui.QPushButton(self.groupBox)
        self.cmdGPSEdit.setGeometry(QtCore.QRect(637, 23, 50, 40))
        self.cmdGPSEdit.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/textedit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdGPSEdit.setIcon(icon5)
        self.cmdGPSEdit.setIconSize(QtCore.QSize(32, 32))
        self.cmdGPSEdit.setObjectName(_fromUtf8("cmdGPSEdit"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 110, 921, 411))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPoleData = QtGui.QWidget()
        self.tabPoleData.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabPoleData.setObjectName(_fromUtf8("tabPoleData"))
        self.dgvPole = QtGui.QTableView(self.tabPoleData)
        self.dgvPole.setGeometry(QtCore.QRect(5, 5, 907, 366))
        self.dgvPole.setFrameShape(QtGui.QFrame.StyledPanel)
        self.dgvPole.setFrameShadow(QtGui.QFrame.Plain)
        self.dgvPole.setObjectName(_fromUtf8("dgvPole"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabpole.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabpole.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabpole.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabpole.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabpole.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabpole.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabpole.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabpole.png")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabPoleData, icon6, _fromUtf8(""))
        self.tabLineData = QtGui.QWidget()
        self.tabLineData.setStyleSheet(_fromUtf8(""))
        self.tabLineData.setObjectName(_fromUtf8("tabLineData"))
        self.dgvLine = QtGui.QTableView(self.tabLineData)
        self.dgvLine.setGeometry(QtCore.QRect(5, 5, 907, 366))
        self.dgvLine.setFrameShape(QtGui.QFrame.StyledPanel)
        self.dgvLine.setFrameShadow(QtGui.QFrame.Plain)
        self.dgvLine.setObjectName(_fromUtf8("dgvLine"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabline.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabline.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabline.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabline.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabline.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabline.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabline.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabline.png")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabLineData, icon7, _fromUtf8(""))
        self.tabProRes = QtGui.QWidget()
        self.tabProRes.setObjectName(_fromUtf8("tabProRes"))
        self.webView = QtWebKit.QWebView(self.tabProRes)
        self.webView.setGeometry(QtCore.QRect(4, 4, 908, 367))
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabres.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabres.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabres.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabres.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabres.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabres.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabres.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ElectricSystems/Resources/FormIcons/protabres.png")), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabProRes, icon8, _fromUtf8(""))
        #frmGPSData.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmGPSData)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmGPSData)

    def retranslateUi(self, frmGPSData):
        frmGPSData.setWindowTitle(_translate("frmGPSData", "GPS Data", None))
        self.label.setText(_translate("frmGPSData", "Project", None))
        self.label_2.setText(_translate("frmGPSData", "Database", None))
        self.label_3.setText(_translate("frmGPSData", "Substation", None))
        self.label_4.setText(_translate("frmGPSData", "Feeder", None))
        self.cmdGPSSave.setToolTip(_translate("frmGPSData", "Save", None))
        self.cmdCreateFeature.setToolTip(_translate("frmGPSData", "Create Fetaure", None))
        self.cmdHelp.setToolTip(_translate("frmGPSData", "Help", None))
        self.cmdClose.setToolTip(_translate("frmGPSData", "Close", None))
        self.label_5.setText(_translate("frmGPSData", "Date", None))
        self.label_6.setText(_translate("frmGPSData", "Group", None))
        self.cmdGPSEdit.setToolTip(_translate("frmGPSData", "Edit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPoleData), _translate("frmGPSData", "Pole Survey Data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLineData), _translate("frmGPSData", "Line Survey Data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProRes), _translate("frmGPSData", "Processing Result", None))

from PyQt4 import QtWebKit
import resources

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    frmGPSData = QtGui.QMainWindow()
    ui = Ui_frmGPSData()
    ui.setupUi(frmGPSData)
    frmGPSData.show()
    sys.exit(app.exec_())

